# Generated by Django 4.2.10 on 2025-05-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
