# Generated by Django 5.2.1 on 2025-05-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
