# Generated by Django 4.2.10 on 2025-05-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='images',
            new_name='image',
        ),
    ]
